name: segment_env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip=25.0
  - pip:
    - geopandas==1.0.1
    - huggingface-hub==0.31.2
    - numpy==1.26.0
    - opencv-python==4.11.0.86
    - pandas==2.2.3
    - pillow==11.2.1
    - pyproj==3.7.1
    - pytz==2025.2
    - rasterio==1.4.3
    - requests==2.32.3
    - scikit-learn==1.6.1
    - scipy==1.15.3
    - segment-anything-py==1.0.1
    - shapely==2.1.0
    - tifffile==2025.5.10
    - torch==2.3.1
    - transformers==4.51.3
    - fastgeodis==1.0.5
    - tqdm==4.67.1
    - matplotlib==3.10.1
    - datasets==3.5.0
    - seaborn==0.13.2
    - accelerate==1.6.0
    - tensorboardX==2.6.2.2